---
################################################################################
#   Section: Organizations
################################################################################
Organizations:

    - &OrdererOrg
        Name: OrdererOrg
        ID: OrdererMSP
        MSPDir: ../organizations/ordererOrganizations/laboratories.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererMSP.admin')"

        OrdererEndpoints:
            - orderer.laboratories.com:7050

    - &Government
        Name: GovernmentMSP
        ID: GovernmentMSP

        MSPDir: ../organizations/peerOrganizations/government.laboratories.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('GovernmentMSP.admin', 'GovernmentMSP.peer', 'GovernmentMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('GovernmentMSP.admin', 'GovernmentMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('GovernmentMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('GovernmentMSP.peer')"

    - &LaboratoryA
        Name: LaboratoryAMSP
        ID: LaboratoryAMSP

        MSPDir: ../organizations/peerOrganizations/laboratoryA.laboratories.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('LaboratoryAMSP.admin', 'LaboratoryAMSP.peer', 'LaboratoryAMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('LaboratoryAMSP.admin', 'LaboratoryAMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('LaboratoryAMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('LaboratoryAMSP.peer')"

################################################################################
#   SECTION: Capabilities
################################################################################
Capabilities:
    Channel: &ChannelCapabilities
        V2_0: true
    Orderer: &OrdererCapabilities
        V2_0: true
    Application: &ApplicationCapabilities
        V2_0: true

################################################################################
#   SECTION: Application
################################################################################
Application: &ApplicationDefaults
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        LifecycleEndorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
        Endorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"

    Capabilities:
        <<: *ApplicationCapabilities
################################################################################
#   SECTION: Orderer
################################################################################
Orderer: &OrdererDefaults
    OrdererType: etcdraft
    Addresses:
        - orderer.laboratories.com:7050
    EtcdRaft:
        Consenters:
        - Host: orderer.laboratories.com
          Port: 7050
          ClientTLSCert: ../organizations/ordererOrganizations/laboratories.com/orderers/orderer.laboratories.com/tls/server.crt
          ServerTLSCert: ../organizations/ordererOrganizations/laboratories.com/orderers/orderer.laboratories.com/tls/server.crt

    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"

################################################################################
#   CHANNEL
################################################################################
Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities

################################################################################
#   Profile
################################################################################
Profiles:

    LaboratoriesGenesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
            Capabilities: *OrdererCapabilities
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Government
                - *LaboratoryA
            Capabilities: *ApplicationCapabilities
